name: ch_v2_1
description: A new Flutter project.

publish_to: "Google Play Store"

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  datetime_picker_formfield: ^2.0.0
  cupertino_icons: ^1.0.0
  flare_flutter: ^3.0.2
  carousel_slider: ^4.0.0
  toggle_switch: ^1.3.0
  custom_switch: ^0.0.1
  flutter_datetime_picker: ^1.2.5
  http: ^0.13.3
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  progress_dialog: ^1.2.1
  page_flip_builder: ^0.1.3
  rules: ^2.0.0
  mime: ^1.0.1
  path_provider: any
  syncfusion_flutter_charts: ^19.4.50
  syncfusion_flutter_pdf: ^19.4.50-beta
  syncfusion_flutter_datepicker: ^19.4.50

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: Nunito
      fonts:
        - asset: asset/font/Nunito.ttf
    - family: Mont
      fonts:
        - asset: asset/font/MontDEMO.otf
    - family: Tai
      fonts:
        - asset: asset/font/Tai.ttf
    - family: Montserrat
      fonts:
        - asset: asset/font/Montserrat.otf
    - family: kohi
      fonts:
        - asset: asset/font/Kohinoor.ttc
