name: ch_v2_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  datetime_picker_formfield: ^1.0.0
  cupertino_icons: ^1.0.0
  flare_flutter: ^1.5.5
  carousel_slider: ^2.3.1
  toggle_switch: "^0.1.8"
  flick_video_player: ^0.1.1
  custom_switch: ^0.0.1
  flutter_datetime_picker: ^1.2.5
  http: ^0.12.0+2
  image_picker: ^0.6.7+7
  shared_preferences: ^0.5.7+3
  intl: ^0.15.7
  progress_dialog: ^1.2.1
  firebase_messaging: ^7.0.3
  sqflite: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: Nunito
      fonts:
        - asset: asset/font/Nunito.ttf
    - family: Mont
      fonts:
        - asset: asset/font/MontDEMO.otf
    - family: Tai
      fonts:
        - asset: asset/font/Tai.ttf
    - family: Montserrat
      fonts:
        - asset: asset/font/Montserrat.otf
